### ISSUE TITLE
Issue with playing videos at google photos

### ISSUE THREAD

**Issue by hiwaryi** [hoyois/clicktoplugin#123] opened 2015-05-30 16:30 UTC
When I try to play videos at google photos page, it says "invalid parameter".
To play videos, I have to disable cicktoflash

**Comment by hoyois** [comment] 2015-05-31 22:58
Thanks for the report! The YouTube killer is the cause of the problem. The following updated version should fix the problem: https://raw.githubusercontent.com/hoyois/plugin-to-html5/master/YouTube.js

**Comment by hoyois** [comment] 2015-06-10 20:45
This should be fixed in v3.1.3.

**Closed by hoyois** 2015-06-10 20:45 UTC
